server{

root /frontend/;
include mime.types;
index index.html;
location / {
try_files $uri $uri/ /index.html;
}
location /api/{
proxy_pass https://backend-container-rjhq.onrender.com;

    # Required for HTTPS upstreams on platforms using SNI-based routing (Render, Vercel, etc)
proxy_ssl_server_name on;
proxy_set_header Host backend-container-rjhq.onrender.com;
proxy_http_version 1.1;
}
}
