server{

root /frontend/;
include mime.types;
index index.html;
location / {
try_files $uri $uri/ /index.html;
}
location /api/{
proxy_pass https://backendstable-production.up.railway.app;
proxy_http_version 1.1;
}
}
