name: CD begin

on:
  workflow_dispatch:
    inputs:
      # environment:
      #   description: 'first cd actions'
      #   default: 'staging'
      #   type: choice
      #   options:
      #     - staging
      tag:
        description: 'tag version'
        default: '1'
jobs:
 deploy:
    runs-on: ubuntu latest
    
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: env creation
        run: |
          cat > .env << EOF
          POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}
          passwordsess=${{secrets.passwordsess}}
          passwordstaff=${{secrets.passwordstaff}}
          passwordusers=${{secrets.passwordusers}}
          passworddb=${{secrets.passworddb}}
          EOF
      - name: docker login
        run: |
          docker login --username aaronica123 --password-stdin <<< `${{secrets.DOCKER_SECRET}}`
      - name: docker pull
        run: |
          docker pull aaronica123/redis_stable:1.0
          docker pull aaronica123/backend_stable:1.0
          docker pull aaronica123/frontend_stable:1.0
          docker pull aaronica123/db_stable:1.0
      - name: docker execute
        run: |
          docker compose -f docker-compose.prod.yml -d
        

      
  

        
      
